### ISSUE TITLE
Migrate to python3

### ISSUE THREAD

**Issue by Zomojo-Geoff** [Zomojo/compiletools#9]
Currently compiletools runs under both python2 and python3.  With under 6 months remaining on the life of python 2, would anybody be adverse to dropping python2 support immediately?  Redhat and Fedora have made it increasingly difficult to simply use /usr/bin/python without qualification.

**Comment by ncoghlan** [comment]
We run all our builds on Py3, so this would be fine by me. As long as you set appropriate metadata, folks running Py2 should continue getting the last version that supported it.

[1] https://packaging.python.org/guides/dropping-older-python-versions/

**Comment by Zomojo-Geoff** [comment]
Thanks @ncoghlan for the packaging tip.  I've started the migration.
